### ISSUE TITLE
Laravel 9 support

### ISSUE THREAD

**Issue by Hesesses** [asantibanez/laravel-blade-sortable#22]
Hello,

I'm getting this when trying to update/install on laravel 9 project:

```
composer require asantibanez/laravel-blade-sortable
Using version ^1.3 for asantibanez/laravel-blade-sortable
./composer.json has been updated
Running composer update asantibanez/laravel-blade-sortable
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires asantibanez/laravel-blade-sortable ^1.3 -> satisfiable by asantibanez/laravel-blade-sortable[v1.3.0].
    - asantibanez/laravel-blade-sortable v1.3.0 requires illuminate/support ^7.0|^8.0 -> found illuminate/support[v7.0.0, ..., 7.x-dev, v8.0.0, ..., 8.x-dev] but these were not loaded, likely because it conflicts with another require.

You can also try re-running composer require with an explicit version constraint, e.g. "composer require asantibanez/laravel-blade-sortable:*" to figure out if any version is installable, or "composer require asantibanez/laravel-blade-sortable:^2.1" if you know which you need.

Installation failed, reverting ./composer.json and ./composer.lock to their original content.

**Comment by asantibanez** [comment]
Resolved by #18

**Comment by tiznull** [comment]
I am still getting this error despite the merge. Am I missing something?

**Comment by nick-massie** [comment]
I am still getting this error too

**Comment by manolismax** [comment]
I am still getting this error too! @asantibanez you never released a new version. The v1.3 has the old version of the composer.json

**Comment by bigenergy** [comment]
> I am still getting this error too! @asantibanez you never released a new version. The v1.3 has the old version of the composer.json

use my fork https://github.com/bigenergy/laravel-blade-sortable
